### ISSUE TITLE
install dependencies at runtime

### ISSUE THREAD

**Issue by Iaotle** [NickVeld/IND-Appointment-Check#8]
Apparently we can install [dependencies at runtime by importing pip](https://stackoverflow.com/questions/17234762/how-to-install-and-import-python-modules-at-runtime).

EDIT: alternatively provide a better explanation of how to install dependencies via pip.

**Comment by NickVeld** [comment]
It is possible to install dependencies it is considered as side effect. Such side effect is very dangerous for the user environment (therefore highly criticized) thing. In our case it can be done but with proper prompting for the user confirmation.

But as for the lack of explanation I see your point.

**Comment by NickVeld** [comment]
@Iaotle 
While checking you changes I have realized that I have replaces `requests` with `urllib.request` in order to get rid of the dependency installation.
So since nothing is needed to be installed there is no need to include auto-installation or make the instruction more difficult describing it.
